### ISSUE TITLE
How can I use this code on HTML5 player default skin?

### ISSUE THREAD

**Issue by hanumantha03** [EndPointCorp/end-point-blog#1468]
In your code you are creating a separate skin for the HTML5 player right? I want to create markers on HTML5 player default skin, is this possible with your code?  if yes, how?

![html5player](https://user-images.githubusercontent.com/32599055/48931289-88053c00-ef1b-11e8-8da1-a5d77250ff2a.PNG)

i want to add markers on the above skin of html5 player.

thanks in advance

**Comment by jonjensen** [comment]
@hanumantha03 Can you please repost your comment on the specific GitHub issue for the blog post you were commenting on? When you created a new issue here it isn't attached to any post, so has no context and readers don't see it. Thanks.
