### ISSUE TITLE
config svn-remote.svn.reposRoot svn://proservices.domainname.com/{foldername}: command returned error: 128

### ISSUE THREAD

**Issue by rinkle25** [EndPointCorp/end-point-blog#1706]
Getting following error when trying to resume the SVN to GIT clone using "git svn fetch"

config svn-remote.svn.reposRoot svn://proservices.domainname.com/{foldername}: command returned error: 128

**Comment by jonjensen** [comment]
Hi. Sorry, but this isn't a general Git support forum! Please check the Git community for help.
