### ISSUE TITLE
Reopen in Container

### ISSUE THREAD

**Issue by eliassal** [EndPointCorp/end-point-blog#1718]
Hi, when we run "Reopen in Container” command. The command will: Read the Dockerfile and create an image based on that. .....", where the image is created,  is it in ubuntu or in the win machine? Same question when running the container, where does it run in ubuntu or windows box?
Thanks

**Comment by jonjensen** [comment]
Hi. This project doesn't accept new issues -- it's a blog, so please comment on the blog post you were reading and people will see your question connected with the right post. Thanks!

**Comment by eliassal** [comment]
it is indicated visit github issue to comment this blog
![WSLBlog](https://user-images.githubusercontent.com/8447864/107853872-a0254680-6e18-11eb-8873-9804624748d2.jpg)

**Comment by jonjensen** [comment]
That is a link to visit a specific GitHub issue (not to create a new issue) for comments about that particular blog post: https://github.com/EndPointCorp/end-point-blog/issues/1641

Opening a new issue means blog authors and readers will never see it. Please post your comment on the correct issue and it is much more likely someone will see it! I hope that helps.
