### ISSUE TITLE
Why all this loop?

### ISSUE THREAD

**Issue by eliassal** [EndPointCorp/end-point-blog#1719]
Maybe I am missing something, but why all this loop, wsl> docker> VSC......If I am not mistaken we can do the exact same thing with docker and VSC without the need to wsl.
What is the point here and where is the added value for ubuntu in wsl as by the end of the day, we are running a container inside windows 10.
Thanks for your explanation

**Comment by jonjensen** [comment]
Hi. This project doesn't accept new issues -- it's a blog, so please comment on the blog post you were reading and people will see your question connected with the right post. Thanks!

**Comment by eliassal** [comment]
It is indicated visit github issues to comment
![WSLBlog](https://user-images.githubusercontent.com/8447864/107853850-83890e80-6e18-11eb-95f6-93657b53d67e.jpg)

**Comment by jonjensen** [comment]
@eliassal That is a link to visit a specific GitHub issue (not to create a new issue) for comments about that particular blog post: https://github.com/EndPointCorp/end-point-blog/issues/1641

Opening a new issue means blog authors and readers will never see it. Please post your comment on the correct issue and it is much more likely someone will see it! I hope that helps.
