### ISSUE TITLE
DIV for each "Marker"

### ISSUE THREAD

**Issue by acbruno** [EndPointCorp/end-point-blog#1747]
Thanks for sharing!

I have a doubt. Is there a possibility to open a DIV for each "Marker"?
For example :

markers: [
{time: 9.5, text: "this"}, // Open a DIV with "this" information
{time: 150, text: "is"}, // close the previous DIV and open another with the information for "is"
{time: 250, text: "so"}, // close the previous DIV and open another with the information for "so"
{time: 370, text: "cool"} /// close the previous DIV and open another one with the information "cool"
],

I only managed using onMarkerReached, but I can't insert the information for each "Marker"

Thank you for your help !

**Comment by jonjensen** [comment]
@acbruno If you'd like to leave a comment on a particular blog post, please follow the link at the bottom of the post, so you can comment in the right one and it'll show up there. Opening a new issue leaves your note unconnected to the article you're talking about. Thanks!
