### ISSUE TITLE
Can perform more frequent commits?

### ISSUE THREAD

**Issue by JamesFraley** [EndPointCorp/end-point-blog#1751]
QUESTION: Is there a way to tell bucardo to commit after every N number of rows? For example, when my network is working perfectly, bucardo can copy about 7500 rows a minute. So, can I instruct it to only copy 7500 updates between commits?

Details: I'm running bucardo in a multimaster replication environment. The systems have a lot of inserts and few updates. The problem is that our network is VERY VERY unreliable. It goes down completely several times a day and has many many smaller outages that last only a minute or 5. Together, this is causing no end of problems. The binning process is the weakness. For example, in the last round, there were 59 bins. I watched it delete all 59 bins. But the network failed just a little after the copying started. so something like:

```
KID (rep) Deleting from target here.sky.geo_point (round 1 of 59)
KID (rep) Deleting from target here.sky.geo_point (round 2 of 59)
...
KID (rep) Deleting from target here.sky.geo_point (round 59 of 59)
KID (rep) /* 1 of 59 */ Copying from there.sky.geo_point
KID (rep) /* 2 of 59 */ Copying from there.sky.geo_point
KID (rep) /* 3 of 59 */ Copying from there.sky.geo_point
```
network failure occurs here and
```
KID (rep) Deleting from target here.sky.geo_point (round 1 of 59)
KID (rep) Deleting from target here.sky.geo_point (round 2 of 59)
. . .
```

and then the network failed. Bucardo restarted from the first of the deleting process. Working like this, replication never finishes.

**Comment by sethjensen1** [comment]
@JamesFraley This repo doesn't accept new issues. Since it's a blog, we have an open issue for each post, linked directly at the bottom of the post. Please comment on that existing issue, so that the post's author can see it, connected to the original post. Thank you!
