### ISSUE TITLE
Can't get working with a romote mongodb

### ISSUE THREAD

**Issue by jorgegfl** [EndPointCorp/end-point-blog#1966]
Hi!
I am trying to get bucardo replication from a local postgresql to a remote mongodb.
I tried successfully replication with all postgresql databases, but when sending replication to a mongodb, it doesnt work.
The command ducardo status displays "no records found"
I'll preciate any help.
Regards, 
Jorge

**Comment by sethjensen1** [comment]
Hi @jorgegfl, the issues in this repo are reserved for blog posts. To leave a comment on a post please go to the associated issue and leave a comment on the issue, instead of creating a new issue.

Thanks for reading!
